/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/prompt-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create a signed task with configured server limits. Registered read tools may read attached inputs; every declared write scope requires owner approval. Run separately through the job run endpoint. */
        post: operations["createPromptJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/identity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIdentity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/manual-actions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["proposeManualAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
                artifact_id: string;
            };
            cookie?: never;
        };
        get: operations["downloadArtifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{room_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        get: operations["getRoom"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{room_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        get: operations["listRoomMembers"];
        put?: never;
        post: operations["joinRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{room_id}/members/{node_id}/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: components["parameters"]["RoomId"];
                node_id: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["heartbeatRoomMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{room_id}/members/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: components["parameters"]["RoomId"];
                node_id: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["leaveRoom"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/room-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRoomSession"];
        put?: never;
        post: operations["configureRoomSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTools"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/peers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPeers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getChain"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chain/{block_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                block_id: components["parameters"]["BlockId"];
            };
            cookie?: never;
        };
        get: operations["getBlock"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stakes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listStakes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["uploadArtifact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listJobs"];
        put?: never;
        post: operations["createJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["acceptJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["runJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["proposeAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/actions/{action_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
                action_id: components["parameters"]["ActionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["decideAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/violations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listViolations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        OperatorSession: {
            token: string;
            expires_at_ms: number;
            node_id: string;
            node_name: string;
        };
        Status: {
            room_id: components["schemas"]["roomId"];
            node_id: components["schemas"]["uuid"];
            node_name: string;
            node_public_key_fingerprint: components["schemas"]["sha256"];
            /** @enum {unknown} */
            node_state: "starting" | "online" | "degraded" | "offline";
            /** @enum {unknown} */
            api_state: "online" | "degraded";
            /** @enum {unknown} */
            provider_state: "configured" | "unconfigured" | "unavailable";
            chain_height: number;
            finalized_height: number;
            updated_at_ms: components["schemas"]["timestampMs"];
        };
        Provider: {
            provider_id: string;
            label: string;
            /** @enum {unknown} */
            kind: "manual" | "ollama" | "openai_compatible";
            /** @enum {unknown} */
            state: "ready" | "unavailable" | "misconfigured";
        };
        Tool: {
            tool_id: components["schemas"]["toolId"];
            label: string;
            description: string;
            version: string;
            argument_schema: Record<string, never>;
            write_scopes: string[];
            output_kinds: ("none" | "text" | "json" | "table" | "artifact")[];
        };
        Peer: {
            node_id: components["schemas"]["uuid"];
            name: string;
            advertised_host: string;
            advertised_port: number;
            public_key_fingerprint: components["schemas"]["sha256"];
            /** @enum {unknown} */
            discovery_state: "discovered" | "expired";
            /** @enum {unknown} */
            connection_state: "disconnected" | "connecting" | "connected" | "failed";
            last_seen_ms: components["schemas"]["timestampMs"];
        };
        Chain: {
            height: number;
            finalized_height: number;
            head_hash: components["schemas"]["sha256"];
            blocks: components["schemas"]["Block"][];
        };
        Block: {
            height: number;
            block_id: components["schemas"]["uuid"];
            hash: components["schemas"]["sha256"];
            previous_hash: components["schemas"]["sha256"];
            creator_fingerprint: components["schemas"]["sha256"];
            created_at_ms: components["schemas"]["timestampMs"];
            transaction_count: number;
            /** @enum {unknown} */
            finality: "proposed" | "confirmed" | "finalized" | "rejected";
        };
        Stake: {
            staker_fingerprint: components["schemas"]["sha256"];
            amount: number;
        };
        Submission: {
            job_id?: components["schemas"]["uuid"];
            submission_id: components["schemas"]["uuid"];
            event_id: components["schemas"]["uuid"];
            /** @enum {unknown} */
            ledger_state: "submitted" | "included" | "finalized" | "rejected";
            event_hash?: components["schemas"]["sha256"] | null;
        };
        /** @enum {unknown} */
        JobStatus: "draft" | "submitted" | "accepted" | "running" | "waiting_approval" | "completed" | "failed" | "expired";
        JobProjection: {
            job_id: components["schemas"]["uuid"];
            room_id: components["schemas"]["roomId"];
            title: string;
            owner_fingerprint: components["schemas"]["sha256"];
            worker_fingerprint?: components["schemas"]["sha256"] | null;
            provider_id: string;
            status: components["schemas"]["JobStatus"];
            latest_sequence: number;
            action_count: number;
            completed_action_count: number;
            pending_approval_count: number;
            created_at_ms: components["schemas"]["timestampMs"];
            updated_at_ms: components["schemas"]["timestampMs"];
            /** @enum {unknown} */
            finality: "pending" | "included" | "finalized" | "rejected";
        };
        Violation: {
            violation_id: components["schemas"]["uuid"];
            job_id: components["schemas"]["uuid"];
            action_id?: components["schemas"]["uuid"] | null;
            /** @enum {unknown} */
            category: "policy" | "signature" | "replay" | "sequence" | "artifact" | "consensus";
            code: string;
            message: string;
            evidence_hash: components["schemas"]["sha256"];
            actor_fingerprint: components["schemas"]["sha256"];
            detected_at_ms: components["schemas"]["timestampMs"];
            /** @enum {unknown} */
            finality: "pending" | "included" | "finalized" | "rejected";
        };
        /** Format: uuid */
        uuid: string;
        /** Prompt-first task */
        "prompt-job-request.schema": {
            instructions: string;
            provider_id: string;
            input_artifact_ids?: components["schemas"]["uuid"][];
        };
        sha256: string;
        apiError: {
            code: string;
            message: string;
            request_id: components["schemas"]["uuid"];
            details?: Record<string, never>;
        };
        toolId: string;
        /** Operator action proposal */
        "manual-action-request.schema": {
            tool_id: components["schemas"]["toolId"];
            arguments: {
                [key: string]: unknown;
            };
            input_artifact_ids: components["schemas"]["uuid"][];
            /** @enum {unknown} */
            expected_output_kind: "none" | "text" | "json" | "table" | "artifact";
        };
        publicKeyPem: string;
        roomId: string;
        consensusParameters: {
            epoch_ms: number;
            max_clock_skew_ms: number;
            finality_depth: number;
            max_connections: number;
            block_reward: number;
            minimum_stake: number;
        };
        timestampMs: number;
        genesisAllocation: {
            public_key: components["schemas"]["publicKeyPem"];
            amount: number;
            /** @description Immutable reserved validator stake; zero denotes a non-validator. */
            stake: number;
        };
        base64Signature: string;
        /** Signed room manifest */
        "room-manifest.schema": {
            /** @constant */
            schema_version: 1;
            room_id: components["schemas"]["roomId"];
            protocol_version: string;
            consensus: {
                /** @constant */
                type: "pos";
                parameters: components["schemas"]["consensusParameters"];
            };
            genesis: {
                block_id: components["schemas"]["uuid"];
                created_at_ms: components["schemas"]["timestampMs"];
                allocations: components["schemas"]["genesisAllocation"][];
            };
            creator_public_key: components["schemas"]["publicKeyPem"];
            created_at_ms: components["schemas"]["timestampMs"];
            signature: components["schemas"]["base64Signature"];
            $defs: {
                consensusParameters: {
                    epoch_ms: number;
                    max_clock_skew_ms: number;
                    finality_depth: number;
                    max_connections: number;
                    block_reward: number;
                    minimum_stake: number;
                };
                genesisAllocation: {
                    public_key: components["schemas"]["publicKeyPem"];
                    amount: number;
                    /** @description Immutable reserved validator stake; zero denotes a non-validator. */
                    stake: number;
                };
            };
        };
        /** Live room member */
        "room-member.schema": {
            /** @constant */
            schema_version: 1;
            room_id: components["schemas"]["roomId"];
            node_id: components["schemas"]["uuid"];
            name: string;
            advertised_host: string;
            advertised_port: number;
            public_key_fingerprint: components["schemas"]["sha256"];
            joined_at_ms: components["schemas"]["timestampMs"];
            last_heartbeat_ms: components["schemas"]["timestampMs"];
        };
        /** Room join request */
        "room-join.schema": {
            /** @constant */
            schema_version: 1;
            node_id: components["schemas"]["uuid"];
            name: string;
            advertised_host: string;
            advertised_port: number;
            public_key_fingerprint: components["schemas"]["sha256"];
        };
        /** Application room session request */
        "room-session-request.schema": {
            /** @enum {unknown} */
            operation: "create" | "join";
            room_id: components["schemas"]["roomId"];
            protocol_version?: string;
            consensus_parameters?: components["schemas"]["consensusParameters"];
            genesis_allocations?: components["schemas"]["genesisAllocation"][];
        } & (unknown & unknown);
        artifactRef: {
            artifact_id: components["schemas"]["uuid"];
            name: string;
            media_type: string;
            size_bytes: number;
            sha256: components["schemas"]["sha256"];
        };
        ruleInput: {
            rule_id?: components["schemas"]["uuid"];
            tool_id: components["schemas"]["toolId"];
            /** @enum {unknown} */
            effect: "allow" | "deny" | "approval_required";
            read_artifact_ids: components["schemas"]["uuid"][];
            write_scopes: string[];
            argument_constraints: Record<string, never>;
        };
        limits: {
            max_actions: number;
            max_runtime_ms_per_action: number;
            max_output_bytes_per_action: number;
        };
        /** Job permission policy */
        "policy.schema": {
            /** @constant */
            schema_version: 1;
            policy_id: components["schemas"]["uuid"];
            job_id: components["schemas"]["uuid"];
            owner_public_key: components["schemas"]["publicKeyPem"];
            rules: (components["schemas"]["ruleInput"] & {
                rule_id: components["schemas"]["uuid"];
            })[];
            limits: components["schemas"]["limits"];
            created_at_ms: components["schemas"]["timestampMs"];
            expires_at_ms?: components["schemas"]["timestampMs"] | null;
            $defs: {
                ruleInput: {
                    rule_id?: components["schemas"]["uuid"];
                    tool_id: components["schemas"]["toolId"];
                    /** @enum {unknown} */
                    effect: "allow" | "deny" | "approval_required";
                    read_artifact_ids: components["schemas"]["uuid"][];
                    write_scopes: string[];
                    argument_constraints: Record<string, never>;
                };
                limits: {
                    max_actions: number;
                    max_runtime_ms_per_action: number;
                    max_output_bytes_per_action: number;
                };
            };
        };
        /** Agent job */
        "job.schema": {
            /** @constant */
            schema_version: 1;
            job_id: components["schemas"]["uuid"];
            room_id: components["schemas"]["roomId"];
            owner_public_key: components["schemas"]["publicKeyPem"];
            title: string;
            instructions: string;
            provider_id: string;
            input_artifacts: components["schemas"]["artifactRef"][];
            policy: components["schemas"]["policy.schema"];
            created_at_ms: components["schemas"]["timestampMs"];
            expires_at_ms?: components["schemas"]["timestampMs"] | null;
        };
        /** Job acceptance */
        "job-acceptance.schema": {
            /** @constant */
            schema_version: 1;
            job_id: components["schemas"]["uuid"];
            worker_public_key: components["schemas"]["publicKeyPem"];
            accepted_at_ms: components["schemas"]["timestampMs"];
        };
        /** Agent action proposal */
        "action.schema": {
            /** @constant */
            schema_version: 1;
            action_id: components["schemas"]["uuid"];
            job_id: components["schemas"]["uuid"];
            action_sequence: number;
            tool_id: components["schemas"]["toolId"];
            arguments: Record<string, never>;
            input_artifact_ids: components["schemas"]["uuid"][];
            /** @enum {unknown} */
            expected_output_kind: "none" | "text" | "json" | "table" | "artifact";
            proposer_public_key: components["schemas"]["publicKeyPem"];
            proposed_at_ms: components["schemas"]["timestampMs"];
        };
        /** Action decision */
        "decision.schema": {
            /** @constant */
            schema_version: 1;
            decision_id: components["schemas"]["uuid"];
            job_id: components["schemas"]["uuid"];
            action_id: components["schemas"]["uuid"];
            /** @enum {unknown} */
            decision: "allow" | "deny" | "approval_required" | "approved" | "rejected";
            /** @enum {unknown} */
            basis: "policy" | "human" | "validator";
            decided_by_public_key: components["schemas"]["publicKeyPem"];
            reason_code: string;
            reason: string;
            policy_hash: components["schemas"]["sha256"];
            decided_at_ms: components["schemas"]["timestampMs"];
        };
        /** Signed action execution receipt */
        "receipt.schema": {
            /** @constant */
            schema_version: 1;
            receipt_id: components["schemas"]["uuid"];
            job_id: components["schemas"]["uuid"];
            action_id: components["schemas"]["uuid"];
            worker_public_key: components["schemas"]["publicKeyPem"];
            tool_id: components["schemas"]["toolId"];
            tool_version: string;
            request_hash: components["schemas"]["sha256"];
            output_hash: components["schemas"]["sha256"];
            output_artifacts: components["schemas"]["artifactRef"][];
            /** @enum {unknown} */
            status: "success" | "failure";
            error?: {
                code: string;
                message: string;
            } | null;
            started_at_ms: components["schemas"]["timestampMs"];
            completed_at_ms: components["schemas"]["timestampMs"];
            signature: components["schemas"]["base64Signature"];
        };
        /** Terminal job result */
        "job-result.schema": {
            /** @constant */
            schema_version: 1;
            job_id: components["schemas"]["uuid"];
            /** @enum {unknown} */
            status: "completed" | "failed";
            output_artifacts: components["schemas"]["artifactRef"][];
            summary: string;
            error?: {
                code: string;
                message: string;
            } | null;
            completed_at_ms: components["schemas"]["timestampMs"];
        };
        /** Security violation */
        "security-violation.schema": {
            /** @constant */
            schema_version: 1;
            violation_id: components["schemas"]["uuid"];
            job_id: components["schemas"]["uuid"];
            action_id?: components["schemas"]["uuid"] | null;
            /** @enum {unknown} */
            category: "policy" | "signature" | "replay" | "sequence" | "artifact" | "consensus";
            reason_code: string;
            message: string;
            evidence_hash: components["schemas"]["sha256"];
            detected_at_ms: components["schemas"]["timestampMs"];
        };
        /** Signed AgentGuard ledger event */
        "agent-event.schema": {
            /** @constant */
            schema_version: 1;
            event_id: components["schemas"]["uuid"];
            /** @enum {unknown} */
            event_type: "job.created" | "job.accepted" | "action.proposed" | "action.allowed" | "action.denied" | "action.approval_required" | "action.approved" | "action.rejected" | "action.completed" | "job.completed" | "job.failed" | "security.violation";
            room_id: components["schemas"]["roomId"];
            job_id: components["schemas"]["uuid"];
            actor_public_key: components["schemas"]["publicKeyPem"];
            sequence: number;
            created_at_ms: components["schemas"]["timestampMs"];
            previous_event_hash: components["schemas"]["sha256"] | null;
            payload: Record<string, never>;
            event_hash: components["schemas"]["sha256"];
            signature: components["schemas"]["base64Signature"];
        } & (unknown & unknown & unknown & unknown & unknown & unknown & unknown);
        /** Create job request */
        "job-create-request.schema": {
            title: string;
            instructions: string;
            provider_id: string;
            input_artifact_ids: components["schemas"]["uuid"][];
            policy: {
                rules: components["schemas"]["ruleInput"][];
                limits: components["schemas"]["limits"];
                expires_at_ms?: components["schemas"]["timestampMs"] | null;
            };
        };
        /** Complete job request */
        "job-complete-request.schema": {
            summary: string;
            output_artifact_ids: components["schemas"]["uuid"][];
        };
        /** Human action decision request */
        "action-decision-request.schema": {
            /** @enum {unknown} */
            decision: "approved" | "rejected";
            reason?: string;
        };
    };
    responses: {
        /** @description Requested resource does not exist */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["apiError"];
            };
        };
        /** @description Request conflicts with current state */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["apiError"];
            };
        };
        /** @description Schema or domain validation failed */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["apiError"];
            };
        };
        /** @description Uploaded request exceeds configured limit */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["apiError"];
            };
        };
        /** @description A required runtime service is unavailable */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["apiError"];
            };
        };
    };
    parameters: {
        RoomId: components["schemas"]["roomId"];
        NodeId: components["schemas"]["uuid"];
        JobId: components["schemas"]["uuid"];
        ActionId: components["schemas"]["uuid"];
        BlockId: components["schemas"]["uuid"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createPromptJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["prompt-job-request.schema"];
            };
        };
        responses: {
            /** @description Task created; response includes job_id */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    access_key: string;
                };
            };
        };
        responses: {
            /** @description Authenticated operator session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatorSession"];
                };
            };
            /** @description Invalid node access key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getIdentity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public node identity */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        node_id: string;
                        node_name: string;
                        public_key: string;
                    };
                };
            };
        };
    };
    proposeManualAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["manual-action-request.schema"];
            };
        };
        responses: {
            /** @description Node constructed and signed the operator proposal */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    downloadArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Integrity-checked private artifact bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ok";
                    };
                };
            };
        };
    };
    createRoom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["room-manifest.schema"];
            };
        };
        responses: {
            /** @description Immutable room manifest stored */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["room-manifest.schema"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    getRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exact stored room manifest */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["room-manifest.schema"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listRoomMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Non-expired room members */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["room-member.schema"][];
                        server_time_ms: components["schemas"]["timestampMs"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    joinRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["room-join.schema"];
            };
        };
        responses: {
            /** @description Membership accepted or refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["room-member.schema"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    heartbeatRoomMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: components["parameters"]["RoomId"];
                node_id: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Heartbeat accepted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    leaveRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: components["parameters"]["RoomId"];
                node_id: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Membership removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application and connected node status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            503: components["responses"]["Unavailable"];
        };
    };
    getRoomSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The manifest actually applied to this node, or null before joining */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        manifest: components["schemas"]["room-manifest.schema"] | null;
                    };
                };
            };
        };
    };
    configureRoomSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["room-session-request.schema"];
            };
        };
        responses: {
            /** @description Local node created or joined the room and returns its verified manifest */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["room-manifest.schema"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            503: components["responses"]["Unavailable"];
        };
    };
    listProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runtime-configured agent providers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Provider"][];
                    };
                };
            };
        };
    };
    listTools: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runtime-registered tool capabilities available for policy construction */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Tool"][];
                    };
                };
            };
        };
    };
    listPeers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Discovered and directly connected peers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Peer"][];
                    };
                };
            };
        };
    };
    getChain: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chain summary and recent blocks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chain"];
                };
            };
        };
    };
    getBlock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                block_id: components["parameters"]["BlockId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Block summary with its ordered AgentGuard events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        block: components["schemas"]["Block"];
                        events: components["schemas"]["agent-event.schema"][];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listStakes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authenticated current stake snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        epoch_seed: components["schemas"]["sha256"];
                        total_stake: number;
                        latest_proposer_fingerprint: components["schemas"]["sha256"] | null;
                        items: components["schemas"]["Stake"][];
                    };
                };
            };
        };
    };
    uploadArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Artifact stored and hashed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["artifactRef"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationError"];
        };
    };
    listJobs: {
        parameters: {
            query?: {
                status?: components["schemas"]["JobStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current job projections */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["JobProjection"][];
                    };
                };
            };
        };
    };
    createJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["job-create-request.schema"];
            };
        };
        responses: {
            /** @description Job event accepted for ledger submission */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job projection and ordered ledger timeline */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        job: components["schemas"]["JobProjection"];
                        action_scopes: {
                            [key: string]: string[];
                        };
                        event_states: {
                            [key: string]: string;
                        };
                        events: components["schemas"]["agent-event.schema"][];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    acceptJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Acceptance event submitted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    runJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Worker run returned; state is the current job projection, not a fabricated running status */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        run_id: components["schemas"]["uuid"];
                        job_id: components["schemas"]["uuid"];
                        /** @enum {unknown} */
                        state: "accepted" | "running" | "waiting_approval" | "completed";
                    };
                };
            };
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
        };
    };
    completeJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["job-complete-request.schema"];
            };
        };
        responses: {
            /** @description Terminal job event submitted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    proposeAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["action.schema"];
            };
        };
        responses: {
            /** @description Action proposal submitted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    decideAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
                action_id: components["parameters"]["ActionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["action-decision-request.schema"];
            };
        };
        responses: {
            /** @description Decision event submitted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    listViolations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Finalized and pending security violations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Violation"][];
                    };
                };
            };
        };
    };
}
