import { CheckCircle2, KeyRound, Network, Plus, Server } from "lucide-react";
import { useMemo, useState, type FormEvent } from "react";
import { useNavigate } from "react-router-dom";
import { useApi } from "../api/ApiContext";
import { ApiClient, ApiError, normalizeApiOrigin } from "../api/client";
import { validateRoomManifest } from "../api/validators";
import type { ConsensusParameters, GenesisAllocation, RoomManifest, RoomSessionRequest } from "../types/api";
import { Copyable } from "../components/Copyable";

function generatedRoomId() { const bytes = crypto.getRandomValues(new Uint8Array(12)); return `room-${Array.from(bytes, byte => byte.toString(16).padStart(2, "0")).join("")}`; }

export function GatewayPage() {
  const navigate = useNavigate(); const { apiOrigin, setApiOrigin } = useApi(); const [origin, setOrigin] = useState(apiOrigin ?? ""); const [mode, setMode] = useState<"join" | "create">("join");
  const [roomId, setRoomId] = useState(""); const [health, setHealth] = useState<"idle" | "checking" | "ok" | "failed">("idle"); const [error, setError] = useState<string | null>(null); const [requestId, setRequestId] = useState<string | null>(null); const [manifest, setManifest] = useState<RoomManifest | null>(null); const [advanced, setAdvanced] = useState(false); const [pending, setPending] = useState(false);
  const [protocolVersion, setProtocolVersion] = useState(""); const [consensus, setConsensus] = useState<Record<keyof ConsensusParameters, string>>({ epoch_ms:"", max_clock_skew_ms:"", finality_depth:"", max_connections:"", block_reward:"", minimum_stake:"" });
  const [allocations, setAllocations] = useState<Array<Record<keyof GenesisAllocation, string>>>([{ public_key:"", amount:"", stake:"" }]);
  const canSubmit = origin.trim() && roomId.trim() && (mode === "join" || (protocolVersion.trim() && Object.values(consensus).every(Boolean) && allocations.every(item => Object.values(item).every(Boolean))));
  const client = useMemo(() => { try { return origin ? new ApiClient(origin) : null; } catch { return null; } }, [origin]);
  const checkHealth = async () => { setError(null); setRequestId(null); setHealth("checking"); try { if (!client) throw new Error("Enter a valid application API URL."); await client.get<{status:"ok"}>("/health"); setHealth("ok"); } catch (cause) { setHealth("failed"); setError(cause instanceof Error ? cause.message : "Health check failed."); if (cause instanceof ApiError) setRequestId(cause.requestId ?? null); } };
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(null); setRequestId(null); setPending(true); try {
    if (!client) throw new Error("Enter a valid application API URL.");
    const body: RoomSessionRequest = mode === "join" ? { operation:"join", room_id:roomId.trim() } : { operation:"create", room_id:roomId.trim(), protocol_version:protocolVersion.trim(), consensus_parameters: Object.fromEntries(Object.entries(consensus).map(([key,value]) => [key, Number(value)])) as ConsensusParameters, genesis_allocations: allocations.map(item => ({ public_key:item.public_key, amount:Number(item.amount), stake:Number(item.stake) })) };
    const result = validateRoomManifest(await client.post<RoomManifest>("/api/room-session", body)); setManifest(result); setApiOrigin(normalizeApiOrigin(origin)); navigate(`/r/${encodeURIComponent(result.room_id)}/overview`);
  } catch (cause) { setError(cause instanceof Error ? cause.message : "Room operation failed."); if (cause instanceof ApiError) setRequestId(cause.requestId ?? null); } finally { setPending(false); } };
  return <main className="gateway-page"><section className="gateway-intro"><div className="gateway-brand"><span>AG</span> AgentGuard Lite</div><p className="eyebrow">Distributed execution flight recorder</p><h1>See what an agent requested, what policy allowed, and what the ledger finalized.</h1><p>A room defines one blockchain network. Its signed manifest fixes genesis and consensus settings.</p><ul><li><Network />Discover peers without a bootstrap address</li><li><KeyRound />Keep signing keys inside the local node</li><li><Server />Load every operational record from your API</li></ul></section>
    <section className="gateway-workspace" aria-labelledby="gateway-title"><div><p className="eyebrow">Connection</p><h2 id="gateway-title">Open an application node</h2></div>
      <label>Application API URL <span>Required; never assumed</span><div className="input-action"><input type="url" value={origin} onChange={event => { setOrigin(event.target.value); setHealth("idle"); }} placeholder="https://your-node.example" /><button type="button" className="button button-secondary" onClick={() => void checkHealth()} disabled={!origin || health === "checking"}>{health === "checking" ? "Checking…" : "Check API"}</button></div></label>
      {health === "ok" && <p className="success-message"><CheckCircle2 />API health check passed.</p>}{health === "failed" && <p className="field-error" role="alert">{error}{requestId && <span className="mono"> Request ID: {requestId}</span>}</p>}
      <div className="tabs" role="tablist" aria-label="Room operation"><button role="tab" aria-selected={mode === "join"} onClick={() => { setMode("join"); setManifest(null); }}>Join room</button><button role="tab" aria-selected={mode === "create"} onClick={() => { setMode("create"); setManifest(null); }}>Create room</button></div>
      <form onSubmit={event => void submit(event)} className="gateway-form">
        <label>Room ID <span>{mode === "create" ? "Generate or enter one" : "Supplied by the room owner"}</span><div className="input-action"><input value={roomId} onChange={event => setRoomId(event.target.value)} required minLength={3} maxLength={128} />{mode === "create" && <button type="button" className="button button-secondary" onClick={() => setRoomId(generatedRoomId())}><Plus />Generate</button>}</div></label>
        {mode === "create" && <><label>Protocol version<input value={protocolVersion} onChange={event => setProtocolVersion(event.target.value)} required /></label><fieldset><legend>Consensus parameters</legend><div className="form-grid">{Object.keys(consensus).map(key => <label key={key}>{key.replaceAll("_"," ")}<input type="number" min="0" value={consensus[key as keyof ConsensusParameters]} onChange={event => setConsensus(current => ({ ...current, [key]:event.target.value }))} required /></label>)}</div></fieldset>
          <fieldset><legend>Genesis allocations</legend>{allocations.map((allocation,index) => <div className="allocation-row" key={index}><label>Public key<textarea value={allocation.public_key} onChange={event => setAllocations(items => items.map((item,i) => i === index ? { ...item, public_key:event.target.value } : item))} required placeholder="Paste the node public key PEM" /></label><label>Amount<input type="number" min="0" value={allocation.amount} onChange={event => setAllocations(items => items.map((item,i) => i === index ? { ...item, amount:event.target.value } : item))} required /></label><label>Reserved stake<input type="number" min="0" value={allocation.stake} onChange={event => setAllocations(items => items.map((item,i) => i === index ? { ...item, stake:event.target.value } : item))} required /></label></div>)}<button type="button" className="button button-secondary" onClick={() => setAllocations(items => [...items,{ public_key:"",amount:"",stake:"" }])}>Add allocation</button></fieldset></>}
        <button className="button button-primary button-full" disabled={!canSubmit || pending}>{pending ? "Verifying…" : mode === "join" ? "Verify manifest and join" : "Review, sign, and create room"}</button>
        {error && health !== "failed" && <p className="field-error" role="alert">{error}{requestId && <span className="mono"> Request ID: {requestId}</span>}</p>}
      </form>
      <button className="disclosure" type="button" aria-expanded={advanced} onClick={() => setAdvanced(value => !value)}>Advanced details</button>{advanced && <div className="advanced-details"><p>Protocol values and the genesis allocation are signed by the local node. Private keys never enter this browser.</p>{roomId && <Copyable value={roomId} label="room ID" compact={false} />}{manifest && <><Copyable value={manifest.creator_public_key} label="creator public key" /><Copyable value={manifest.signature} label="manifest signature" /></>}</div>}
    </section></main>;
}
