import { useState } from "react";
import { useParams } from "react-router-dom";
import { useBlock, useChain } from "../api/hooks";
import { PageHeader } from "../components/AppShell";
import { Copyable } from "../components/Copyable";
import { Inspector } from "../components/Inspector";
import { EmptyState, ErrorState, Skeleton } from "../components/States";
import { StatusBadge } from "../components/StatusBadge";
import { formatTimestamp } from "../utils/format";

export function LedgerPage(){const roomId=useParams().roomId??"";const chain=useChain(roomId,100);const[selected,setSelected]=useState<string|null>(null);const block=useBlock(roomId,selected);return <div className="page"><PageHeader title="Ledger" detail="Blocks, finality, and linked Certa events from the active node."/><section className="surface"><header className="section-heading"><div><h2>Chain</h2><p>Height {chain.data?.height??"—"}; finalized through {chain.data?.finalized_height??"—"}.</p></div>{chain.data&&<Copyable value={chain.data.head_hash} label="head hash"/>}</header>{chain.isPending?<Skeleton rows={8}/>:chain.error?<ErrorState error={chain.error}/>:!chain.data.blocks.length?<EmptyState title="No blocks returned" detail="The active node did not return a genesis or recent block summary."/>:<div className="table-wrap"><table><thead><tr><th>Height</th><th>Hash link</th><th>Creator</th><th>Entries</th><th>Finality</th><th>Time</th></tr></thead><tbody>{chain.data.blocks.map(item=><tr key={item.block_id} className="clickable-row" onClick={()=>setSelected(item.block_id)}><td><button className="link-button" onClick={()=>setSelected(item.block_id)}>{item.height === 0 ? "0 · Genesis" : item.height}</button></td><td><Copyable value={item.hash} label="block hash"/><small>← <span className="mono">{item.previous_hash.slice(0,10)}…</span></small></td><td><Copyable value={item.creator_fingerprint} label="creator fingerprint"/></td><td>{item.transaction_count}</td><td><StatusBadge value={item.finality}/></td><td>{formatTimestamp(item.created_at_ms)}</td></tr>)}</tbody></table></div>}</section><Inspector title="Block inspector" open={Boolean(selected)} onClose={()=>setSelected(null)}>{block.isPending?<Skeleton/>:block.error?<ErrorState error={block.error}/>:block.data&&<><StatusBadge value={block.data.block.finality}/><dl className="definition-list"><dt>Height</dt><dd>{block.data.block.height}</dd><dt>Block ID</dt><dd><Copyable value={block.data.block.block_id} label="block ID" compact={false}/></dd><dt>Hash</dt><dd><Copyable value={block.data.block.hash} label="block hash" compact={false}/></dd><dt>Previous hash</dt><dd><Copyable value={block.data.block.previous_hash} label="previous block hash" compact={false}/></dd><dt>Creator</dt><dd><Copyable value={block.data.block.creator_fingerprint} label="creator fingerprint" compact={false}/></dd><dt>Timestamp</dt><dd>{formatTimestamp(block.data.block.created_at_ms)}</dd></dl><h3>Linked events</h3>{block.data.events.length?<ul className="plain-list">{block.data.events.map(event=><li key={event.event_id}><code>{event.event_type}</code><Copyable value={event.event_hash} label="event hash"/></li>)}</ul>:<p>{block.data.block.height === 0 ? "Genesis is the network’s starting block, created when the room was set up. It is not a task or agent result. Its previous hash is all zeros because no earlier block exists." : "No Certa events are linked to this block."}</p>}</>}</Inspector></div>}
