import { AlertTriangle, ArrowRight, Blocks, CheckCircle2, Clock3, Network as NetworkIcon, ShieldAlert, Workflow } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { useChain, useJobs, usePeers, useStakes, useStatus, useViolations } from "../api/hooks";
import { CreateJobButton, PageHeader } from "../components/AppShell";
import { Copyable } from "../components/Copyable";
import { EmptyState, ErrorState, Skeleton, StaleDataBanner } from "../components/States";
import { StatusBadge } from "../components/StatusBadge";
import { formatTimestamp, shortId } from "../utils/format";

export function OverviewPage() {
  const roomId = useParams().roomId ?? ""; const status = useStatus(); const peers = usePeers(roomId); const jobs = useJobs(roomId); const chain = useChain(roomId, 8); const stakes = useStakes(roomId); const violations = useViolations(roomId);
  const queries = [status, peers, jobs, chain, stakes, violations]; const firstError = queries.find(query => query.error)?.error; const pendingApprovals = jobs.data?.reduce((sum, job) => sum + job.pending_approval_count, 0) ?? 0; const activeJobs = jobs.data?.filter(job => !["completed","failed","expired"].includes(job.status)).length ?? 0; const connected = peers.data?.filter(peer => peer.connection_state === "connected").length ?? 0;
  return <div className="page"><PageHeader eyebrow="Room operations" title="Overview" detail="Live node, execution, and consensus health." action={<CreateJobButton />} />
    {queries.some(query => query.isRefetchError) && <StaleDataBanner updatedAt={Math.min(...queries.map(query => query.dataUpdatedAt || Date.now()))} onRetry={() => void Promise.all(queries.map(query => query.refetch()))} />}
    {firstError && !status.data ? <ErrorState error={firstError} onRetry={() => void Promise.all(queries.map(query => query.refetch()))} /> : <>
      <section className="status-strip" aria-label="Room status"><StatusCell icon={<CheckCircle2 />} label="Service" value={status.data?.api_state ?? "Loading"} /><StatusCell icon={<NetworkIcon />} label="Peers" value={`${connected} connected / ${peers.data?.length ?? 0} discovered`} /><StatusCell icon={<Blocks />} label="Height" value={`${chain.data?.height ?? "—"} / ${chain.data?.finalized_height ?? "—"} finalized`} /><StatusCell icon={<Clock3 />} label="Approvals" value={String(pendingApprovals)} /><StatusCell icon={<Workflow />} label="Active jobs" value={String(activeJobs)} /><StatusCell icon={<ShieldAlert />} label="Violations" value={String(violations.data?.length ?? 0)} /></section>
      <div className="dashboard-grid"><section className="surface attention-panel"><header><h2>Needs attention</h2></header>{!jobs.data ? <Skeleton /> : pendingApprovals === 0 && status.data?.provider_state === "configured" ? <p className="calm-state"><CheckCircle2 />No operator action is required.</p> : <ul className="attention-list">{status.data?.provider_state !== "configured" && <li><AlertTriangle /><span><strong>Provider {status.data?.provider_state}</strong><small>Worker runs may require manual proposals.</small></span></li>}{jobs.data.filter(job => job.pending_approval_count).map(job => <li key={job.job_id}><Clock3 /><span><strong>{job.title}</strong><small>{job.pending_approval_count} approval pending</small></span><Link to={`/r/${roomId}/jobs/${job.job_id}`}>Review <ArrowRight /></Link></li>)}</ul>}</section>
        <section className="surface consensus-panel"><header><h2>Consensus pulse</h2></header>{!stakes.data ? <Skeleton rows={3} /> : <dl className="definition-list"><dt>Epoch seed</dt><dd><Copyable value={stakes.data.epoch_seed} label="epoch seed" /></dd><dt>Total authenticated stake</dt><dd>{stakes.data.total_stake.toLocaleString()}</dd><dt>Latest proposer</dt><dd>{stakes.data.latest_proposer_fingerprint ? <Copyable value={stakes.data.latest_proposer_fingerprint} label="proposer fingerprint" /> : "No proposer recorded"}</dd><dt>Finality lag</dt><dd>{Math.max(0,(chain.data?.height ?? 0)-(chain.data?.finalized_height ?? 0))} blocks</dd></dl>}</section>
      </div>
      <section className="surface"><header className="section-heading"><div><h2>Recent work</h2><p>Most recently changed jobs and truthful ledger state.</p></div><Link to={`/r/${roomId}/jobs`}>View all jobs</Link></header>{jobs.isPending ? <Skeleton /> : !jobs.data?.length ? <EmptyState title="No jobs have been submitted in this room." detail="Create a job to begin a policy-governed execution." action={<CreateJobButton />} /> : <div className="job-cards">{jobs.data.slice(0,4).map(job => <Link className="job-card" key={job.job_id} to={`/r/${roomId}/jobs/${job.job_id}`}><span><StatusBadge value={job.status} /><StatusBadge value={job.finality} /></span><h3>{job.title}</h3><p>{job.completed_action_count} of {job.action_count} actions completed</p><small>Updated {formatTimestamp(job.updated_at_ms)}</small></Link>)}</div>}</section>
      <section className="surface"><header className="section-heading"><div><h2>Recent blocks</h2><p>Consensus summaries returned by the active node.</p></div><Link to={`/r/${roomId}/ledger`}>Open ledger</Link></header>{chain.isPending ? <Skeleton /> : !chain.data?.blocks.length ? <EmptyState title="No blocks beyond genesis" detail="Accepted events will appear after block production." /> : <div className="table-wrap"><table><thead><tr><th>Height</th><th>Hash</th><th>Creator</th><th>Events</th><th>Finality</th><th>Time</th></tr></thead><tbody>{chain.data.blocks.map(block => <tr key={block.block_id}><td>{block.height}</td><td><Copyable value={block.hash} label="block hash" /></td><td className="mono">{shortId(block.creator_fingerprint)}</td><td>{block.transaction_count}</td><td><StatusBadge value={block.finality} /></td><td>{formatTimestamp(block.created_at_ms)}</td></tr>)}</tbody></table></div>}</section>
    </>}</div>;
}

function StatusCell({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="status-cell">{icon}<span><small>{label}</small><strong>{value}</strong></span></div>; }
