import { ShieldCheck } from "lucide-react";
import { useMemo, useState } from "react";
import { useParams, useSearchParams } from "react-router-dom";
import { useViolations } from "../api/hooks";
import { PageHeader } from "../components/AppShell";
import { Copyable } from "../components/Copyable";
import { Inspector } from "../components/Inspector";
import { EmptyState, ErrorState, Skeleton } from "../components/States";
import { StatusBadge } from "../components/StatusBadge";
import type { Violation } from "../types/api";
import { formatTimestamp, titleCase } from "../utils/format";

export function SecurityPage(){const roomId=useParams().roomId??"";const violations=useViolations(roomId);const[params,setParams]=useSearchParams();const category=params.get("category")??"";const[selected,setSelected]=useState<Violation|null>(null);const filtered=useMemo(()=>(violations.data??[]).filter(item=>!category||item.category===category),[violations.data,category]);const categories=Array.from(new Set((violations.data??[]).map(item=>item.category)));return <div className="page"><PageHeader eyebrow="Policy and validator evidence" title="Security" detail="Rejected behavior is displayed with reason codes and evidence hashes."/><div className="filter-bar"><label>Category<select value={category} onChange={event=>{const next=new URLSearchParams(params);if(event.target.value)next.set("category",event.target.value);else next.delete("category");setParams(next)}}><option value="">All categories</option>{categories.map(item=><option key={item} value={item}>{titleCase(item)}</option>)}</select></label></div><section className="surface">{violations.isPending?<Skeleton/>:violations.error?<ErrorState error={violations.error}/>:!filtered.length?<EmptyState title="No security violations are recorded for this room." detail="Policy denials and validator rejections will appear here when observed." action={<ShieldCheck/>}/>:<div className="table-wrap"><table><thead><tr><th>Time</th><th>Category</th><th>Reason</th><th>Job / action</th><th>Evidence</th><th>Finality</th></tr></thead><tbody>{filtered.map(item=><tr key={item.violation_id} className="clickable-row" onClick={()=>setSelected(item)}><td>{formatTimestamp(item.detected_at_ms)}</td><td>{titleCase(item.category)}</td><td><button className="link-button" onClick={()=>setSelected(item)}>{item.code}</button><small>{item.message}</small></td><td><Copyable value={item.job_id} label="job ID"/>{item.action_id&&<Copyable value={item.action_id} label="action ID"/>}</td><td><Copyable value={item.evidence_hash} label="evidence hash"/></td><td><StatusBadge value={item.finality}/></td></tr>)}</tbody></table></div>}</section><Inspector title="Violation evidence" open={Boolean(selected)} onClose={()=>setSelected(null)}>{selected&&<><StatusBadge value={selected.finality}/><h3>{selected.code}</h3><p>{selected.message}</p><dl className="definition-list"><dt>Category</dt><dd>{titleCase(selected.category)}</dd><dt>Detected</dt><dd>{formatTimestamp(selected.detected_at_ms)}</dd><dt>Violation ID</dt><dd><Copyable value={selected.violation_id} label="violation ID" compact={false}/></dd><dt>Job ID</dt><dd><Copyable value={selected.job_id} label="job ID" compact={false}/></dd><dt>Evidence hash</dt><dd><Copyable value={selected.evidence_hash} label="evidence hash" compact={false}/></dd><dt>Detector</dt><dd><Copyable value={selected.actor_fingerprint} label="detector fingerprint" compact={false}/></dd></dl></>}</Inspector></div>}
