import { Check, Clipboard, LogOut } from "lucide-react";
import { useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { useApi } from "../api/ApiContext";
import { useProviders, useStatus } from "../api/hooks";
import { PageHeader } from "../components/AppShell";
import { Copyable } from "../components/Copyable";
import { ErrorState, Skeleton } from "../components/States";
import { StatusBadge } from "../components/StatusBadge";

export function SettingsPage(){const roomId=useParams().roomId??"";const navigate=useNavigate();const{apiOrigin,pollIntervalMs,setApiOrigin}=useApi();const status=useStatus();const providers=useProviders();const[copied,setCopied]=useState(false);if(status.isPending)return <div className="page"><PageHeader title="Runtime settings"/><Skeleton/></div>;if(status.error)return <div className="page"><PageHeader title="Runtime settings"/><ErrorState error={status.error}/></div>;const diagnostics={frontend_version:__APP_VERSION__,api_origin:apiOrigin,room_id:roomId,node_name:status.data.node_name,node_id:status.data.node_id,node_public_key_fingerprint:status.data.node_public_key_fingerprint,node_state:status.data.node_state,api_state:status.data.api_state,provider_state:status.data.provider_state,chain_height:status.data.chain_height,finalized_height:status.data.finalized_height,poll_interval_ms:pollIntervalMs};const copy=async()=>{await navigator.clipboard.writeText(JSON.stringify(diagnostics,null,2));setCopied(true);window.setTimeout(()=>setCopied(false),1500)};return <div className="page"><PageHeader eyebrow="Safe runtime summary" title="Settings" detail="No credentials, private keys, artifact bodies, or absolute storage paths are shown."/><div className="settings-grid"><section className="surface"><h2>Application</h2><dl className="definition-list"><dt>API origin</dt><dd className="mono break-all">{apiOrigin}</dd><dt>Polling interval</dt><dd>{pollIntervalMs.toLocaleString()} ms</dd><dt>Frontend version</dt><dd>{__APP_VERSION__}</dd><dt>Room</dt><dd><Copyable value={roomId} label="room ID" compact={false}/></dd></dl></section><section className="surface"><h2>Node identity</h2><dl className="definition-list"><dt>Name</dt><dd>{status.data.node_name}</dd><dt>Node ID</dt><dd><Copyable value={status.data.node_id} label="node ID" compact={false}/></dd><dt>Fingerprint</dt><dd><Copyable value={status.data.node_public_key_fingerprint} label="public key fingerprint" compact={false}/></dd><dt>State</dt><dd><StatusBadge value={status.data.node_state}/></dd></dl></section><section className="surface"><h2>Providers</h2>{providers.data?.length?<ul className="plain-list">{providers.data.map(provider=><li key={provider.provider_id}><span><strong>{provider.label}</strong><small>{provider.kind}</small></span><StatusBadge value={provider.state}/></li>)}</ul>:<p>No providers are configured.</p>}</section><section className="surface"><h2>Operator actions</h2><div className="button-stack"><button className="button button-secondary" onClick={()=>void copy()}>{copied?<Check/>:<Clipboard/>}{copied?"Diagnostics copied":"Copy sanitized diagnostics"}</button><button className="button button-danger" onClick={()=>{setApiOrigin(null);navigate("/")}}><LogOut/>Leave console and clear API choice</button></div></section></div></div>}
